-- 📋 Supabase SQL Editor-এ এই সম্পূর্ণ SQL চালাও (Ctrl+A > Run)

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz default now()
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  receiver_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  created_at timestamptz default now()
);

alter table profiles enable row level security;
alter table messages enable row level security;

-- Profiles: সব authenticated users দেখতে পারবে
create policy "profiles readable"
on profiles for select to authenticated using (true);

-- Profiles: শুধু নিজের profile তৈরি করতে পারবে
create policy "own profile insert"
on profiles for insert to authenticated with check (id = auth.uid());

-- Messages: শুধু sender বা receiver দেখতে পারবে
create policy "messages readable by participants"
on messages for select to authenticated
using (sender_id = auth.uid() or receiver_id = auth.uid());

-- Messages: শুধু নিজের message পাঠাতে পারবে
create policy "send own messages"
on messages for insert to authenticated
with check (sender_id = auth.uid());

-- Auto-create profile যখন নতুন user signup করে
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email) values (new.id, new.email);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();